Система Автоматизированного Программирования Техтран+

Wednesday, September 23, 2020

Файл: ВЕРСИЯ 5
Ошибка при загрузке ВЕРСИЯ 5
Ошибки

Файл: ДЕТАЛЬ ''
Ошибка при загрузке ДЕТАЛЬ ''
Ошибки

Файл: СТАНОК '160HT ПРУТКОВЫЙ',214
Ошибка при загрузке СТАНОК '160HT ПРУТКОВЫЙ',214
Ошибки

Файл: ПР0=ХПАР,0,УБ
Ошибка при загрузке ПР0=ХПАР,0,УБ
Ошибки

Файл: ПР1=УПАР,0,ХБ
Ошибка при загрузке ПР1=УПАР,0,ХБ
Ошибки

Файл: ТЧ0=ПЕРЕСЕЧ,ПР1,ПР0
Ошибка при загрузке ТЧ0=ПЕРЕСЕЧ,ПР1,ПР0
Ошибки

Файл: ПР2=УПАР,13.05,ХБ
Ошибка при загрузке ПР2=УПАР,13.05,ХБ
Ошибки

Файл: ПР3=ХПАР,337.8/2,УБ
Ошибка при загрузке ПР3=ХПАР,337.8/2,УБ
Ошибки

Файл: ПР4=ХПАР,290.04/2,УБ
Ошибка при загрузке ПР4=ХПАР,290.04/2,УБ
Ошибки

Файл: ТЧ1=ПЕРЕСЕЧ,ПР1,ПР3
Ошибка при загрузке ТЧ1=ПЕРЕСЕЧ,ПР1,ПР3
Ошибки

Файл: ТЧ2=ПЕРЕСЕЧ,ПР2,ПР3
Ошибка при загрузке ТЧ2=ПЕРЕСЕЧ,ПР2,ПР3
Ошибки

Файл: ТЧ3=ПЕРЕСЕЧ,ПР4,ПР2
Ошибка при загрузке ТЧ3=ПЕРЕСЕЧ,ПР4,ПР2
Ошибки

Файл: ТЧ4=ПЕРЕСЕЧ,ПР1,ПР4
Ошибка при загрузке ТЧ4=ПЕРЕСЕЧ,ПР1,ПР4
Ошибки

Файл: КОНТУР К0=ИЗ,ТЧ4,ХБ
Ошибка при загрузке КОНТУР К0=ИЗ,ТЧ4,ХБ
Ошибки

Файл:  ВТОЧКУ,ТЧ3
Ошибка при загрузке  ВТОЧКУ,ТЧ3
Ошибки

Файл:  ВТОЧКУ,ТЧ2
Ошибка при загрузке  ВТОЧКУ,ТЧ2
Ошибки

Файл:  ВТОЧКУ,ТЧ1
Ошибка при загрузке  ВТОЧКУ,ТЧ1
Ошибки

Файл:  ВТОЧКУ,ТЧ4
Ошибка при загрузке  ВТОЧКУ,ТЧ4
Ошибки

Файл: КОНКОН
Ошибка при загрузке КОНКОН
Ошибки

Файл: ПР5=УПАР,9.2,ХБ
Ошибка при загрузке ПР5=УПАР,9.2,ХБ
Ошибки

Файл: ПР6=ХПАР,320.04/2,УБ
Ошибка при загрузке ПР6=ХПАР,320.04/2,УБ
Ошибки

Файл: ТЧ5=ПЕРЕСЕЧ,ПР6,ПР5
Ошибка при загрузке ТЧ5=ПЕРЕСЕЧ,ПР6,ПР5
Ошибки

Файл: КОНТУР К1=ИЗ,ТОЧКА(К0,0),ХБ
Ошибка при загрузке КОНТУР К1=ИЗ,ТОЧКА(К0,0),ХБ
Ошибки

Файл: ТЧ6=ПЕРЕСЕЧ,ПР4,ПР5
Ошибка при загрузке ТЧ6=ПЕРЕСЕЧ,ПР4,ПР5
Ошибки

Файл: ТЧ7=ПЕРЕСЕЧ,ПР6,ПР2
Ошибка при загрузке ТЧ7=ПЕРЕСЕЧ,ПР6,ПР2
Ошибки

Файл:  ВТОЧКУ,ТЧ4
Ошибка при загрузке  ВТОЧКУ,ТЧ4
Ошибки

Файл: ПР7=ХПАР,335.12/2,УБ
Ошибка при загрузке ПР7=ХПАР,335.12/2,УБ
Ошибки

Файл: ТЧ8=ПЕРЕСЕЧ,ПР7,ПР2
Ошибка при загрузке ТЧ8=ПЕРЕСЕЧ,ПР7,ПР2
Ошибки

Файл: ПР8=УПАР,11.98,ХБ
Ошибка при загрузке ПР8=УПАР,11.98,ХБ
Ошибки

Файл: ТЧ9=ПЕРЕСЕЧ,ПР8,ПР7
Ошибка при загрузке ТЧ9=ПЕРЕСЕЧ,ПР8,ПР7
Ошибки

Файл: ТЧ10=ПЕРЕСЕЧ,ПР7,ПР1
Ошибка при загрузке ТЧ10=ПЕРЕСЕЧ,ПР7,ПР1
Ошибки

Файл: ТЧ11=ПЕРЕСЕЧ,ПР6,ПР8
Ошибка при загрузке ТЧ11=ПЕРЕСЕЧ,ПР6,ПР8
Ошибки

Файл:  ВТОЧКУ,ТЧ4
Ошибка при загрузке  ВТОЧКУ,ТЧ4
Ошибки

Файл:  ВТОЧКУ,ТЧ6
Ошибка при загрузке  ВТОЧКУ,ТЧ6
Ошибки

Файл:  ВТОЧКУ,ТЧ5
Ошибка при загрузке  ВТОЧКУ,ТЧ5
Ошибки

Файл:  ВТОЧКУ,ТЧ11
Ошибка при загрузке  ВТОЧКУ,ТЧ11
Ошибки

Файл:  ВТОЧКУ,ТЧ9
Ошибка при загрузке  ВТОЧКУ,ТЧ9
Ошибки

Файл:  ВТОЧКУ,ТЧ10
Ошибка при загрузке  ВТОЧКУ,ТЧ10
Ошибки

Файл:  ВТОЧКУ,ТЧ4
Ошибка при загрузке  ВТОЧКУ,ТЧ4
Ошибки

Файл: КОНКОН
Ошибка при загрузке КОНКОН
Ошибки

Файл: К1,4: ФАСКА 1,1
Ошибка при загрузке К1,4: ФАСКА 1,1
Ошибки

Файл: К1,3: ФАСКА 0.5,0.5
Ошибка при загрузке К1,3: ФАСКА 0.5,0.5
Ошибки

Файл: К1,1: ФАСКА 1,1
Ошибка при загрузке К1,1: ФАСКА 1,1
Ошибки

Файл: ЗАЖИМ,ДЕТАЛЬ,К1,ВНУТРИ,К0,КООРД,0,СЛЕВА,ШИРИНА,10,ВЫСОТА,30,РАСТ,АБСОЛЮТ,0,3
Ошибка при загрузке ЗАЖИМ,ДЕТАЛЬ,К1,ВНУТРИ,К0,КООРД,0,СЛЕВА,ШИРИНА,10,ВЫСОТА,30,РАСТ,АБСОЛЮТ,0,3
Ошибки

Файл: КООРДСТ,РЕГ,54
Ошибка при загрузке КООРДСТ,РЕГ,54
Ошибки

Файл: СДВИГ,0,0
Ошибка при загрузке СДВИГ,0,0
Ошибки

Файл: ТЧКСМЕН,150,450
Ошибка при загрузке ТЧКСМЕН,150,450
Ошибки

Файл: ТЧКСМЕН,50,200
Ошибка при загрузке ТЧКСМЕН,50,200
Ошибки

Файл: ИНСТР РЕЗЕЦ1=РЕЗЕЦ ТОЧЕНИЕ,'РЕЗЕЦ1',1,УСТАНОВ,3,ПЛАСТИНА,4,УГОЛ,93,7,РАДИУС,1.2,КРОМКА,12,8,6,4,ПОПРАВКА ВКЛ,НОМГОЛОВ,СЛЕВА
Ошибка при загрузке ИНСТР РЕЗЕЦ1=РЕЗЕЦ ТОЧЕНИЕ,'РЕЗЕЦ1',1,УСТАНОВ,3,ПЛАСТИНА,4,УГОЛ,93,7,РАДИУС,1.2,КРОМКА,12,8,6,4,ПОПРАВКА ВКЛ,НОМГОЛОВ,СЛЕВА
Ошибки

Файл: РЕЗЕЦ1:ШПИНДЛ,ОБМИН,200,ПОЧС,ДИАП,1
Ошибка при загрузке РЕЗЕЦ1:ШПИНДЛ,ОБМИН,200,ПОЧС,ДИАП,1
Ошибки

Файл: РЕЗЕЦ1:ПОДАЧА ЧЕРН,ММОБ,0.35
Ошибка при загрузке РЕЗЕЦ1:ПОДАЧА ЧЕРН,ММОБ,0.35
Ошибки

Файл: РЕЗЕЦ1:ПОДАЧА ЧИСТ,ММОБ,0.2
Ошибка при загрузке РЕЗЕЦ1:ПОДАЧА ЧИСТ,ММОБ,0.2
Ошибки

Файл: РЕЗЕЦ1:ОХЛАД ,ЖИДК
Ошибка при загрузке РЕЗЕЦ1:ОХЛАД ,ЖИДК
Ошибки

Файл: ЗАГРУЗ РЕЗЕЦ1
Ошибка при загрузке ЗАГРУЗ РЕЗЕЦ1
Ошибки

Файл: ЗОНА ПОЧС,3,4
Ошибка при загрузке ЗОНА ПОЧС,3,4
Ошибки

Файл: ГЛУБИНА 1.6,ФИКС
Ошибка при загрузке ГЛУБИНА 1.6,ФИКС
Ошибки

Файл: БЕЗОПРСТ 1
Ошибка при загрузке БЕЗОПРСТ 1
Ошибки

Файл: ПРИПУСК 0,0
Ошибка при загрузке ПРИПУСК 0,0
Ошибки

Файл: ОТСКОК 1
Ошибка при загрузке ОТСКОК 1
Ошибки

Файл: КРОМКА ВСПОМ
Ошибка при загрузке КРОМКА ВСПОМ
Ошибки

Файл: ЧИСТ ВКЛ
Ошибка при загрузке ЧИСТ ВКЛ
Ошибки

Файл: ЧЕРН ВКЛ
Ошибка при загрузке ЧЕРН ВКЛ
Ошибки

Файл: ПОДРЕЗКА,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке ПОДРЕЗКА,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: ЗОНА ПРЧС,2,1
Ошибка при загрузке ЗОНА ПРЧС,2,1
Ошибки

Файл: ГЛУБИНА 0.5,ФИКС
Ошибка при загрузке ГЛУБИНА 0.5,ФИКС
Ошибки

Файл: ПРИПУСК 0.5,0
Ошибка при загрузке ПРИПУСК 0.5,0
Ошибки

Файл: КРОМКА ГЛАВН
Ошибка при загрузке КРОМКА ГЛАВН
Ошибки

Файл: ТОЧЕНИЕ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке ТОЧЕНИЕ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: ЗОНА ПРЧС,3,1
Ошибка при загрузке ЗОНА ПРЧС,3,1
Ошибки

Файл: ПРИПУСК 0,0
Ошибка при загрузке ПРИПУСК 0,0
Ошибки

Файл: ЧЕРН ВЫКЛ
Ошибка при загрузке ЧЕРН ВЫКЛ
Ошибки

Файл: ТОЧЕНИЕ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке ТОЧЕНИЕ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: ИНСТР РЕЗЕЦ2=РЕЗЕЦ ТОЧЕНИЕ,'РЕЗЕЦ2',2,УСТАНОВ,2,ПЛАСТИНА,4,УГОЛ,93,7,РАДИУС,0.8,КРОМКА,12,8,6,4,ПОПРАВКА ВКЛ,НОМГОЛОВ,СЛЕВА
Ошибка при загрузке ИНСТР РЕЗЕЦ2=РЕЗЕЦ ТОЧЕНИЕ,'РЕЗЕЦ2',2,УСТАНОВ,2,ПЛАСТИНА,4,УГОЛ,93,7,РАДИУС,0.8,КРОМКА,12,8,6,4,ПОПРАВКА ВКЛ,НОМГОЛОВ,СЛЕВА
Ошибки

Файл: РЕЗЕЦ2:ШПИНДЛ,ОБМИН,300,ПОЧС,ДИАП,1
Ошибка при загрузке РЕЗЕЦ2:ШПИНДЛ,ОБМИН,300,ПОЧС,ДИАП,1
Ошибки

Файл: РЕЗЕЦ2:ПОДАЧА ЧЕРН,ММОБ,0.32
Ошибка при загрузке РЕЗЕЦ2:ПОДАЧА ЧЕРН,ММОБ,0.32
Ошибки

Файл: РЕЗЕЦ2:ПОДАЧА ЧИСТ,ММОБ,0.2
Ошибка при загрузке РЕЗЕЦ2:ПОДАЧА ЧИСТ,ММОБ,0.2
Ошибки

Файл: РЕЗЕЦ2:ОХЛАД ,ЖИДК
Ошибка при загрузке РЕЗЕЦ2:ОХЛАД ,ЖИДК
Ошибки

Файл: ВОЗВРАТ
Ошибка при загрузке ВОЗВРАТ
Ошибки

Файл: ТЕХОСТ
Ошибка при загрузке ТЕХОСТ
Ошибки

Файл: ЗАГРУЗ РЕЗЕЦ2
Ошибка при загрузке ЗАГРУЗ РЕЗЕЦ2
Ошибки

Файл: ЗОНА ПРЧС,7,5
Ошибка при загрузке ЗОНА ПРЧС,7,5
Ошибки

Файл: ЗОНА ПРЧС,7,5
Ошибка при загрузке ЗОНА ПРЧС,7,5
Ошибки

Файл: ГЛУБИНА 1,ФИКС
Ошибка при загрузке ГЛУБИНА 1,ФИКС
Ошибки

Файл: ПРИПУСК 0.5,1
Ошибка при загрузке ПРИПУСК 0.5,1
Ошибки

Файл: КРОМКА ВСПОМ
Ошибка при загрузке КРОМКА ВСПОМ
Ошибки

Файл: ЧЕРН ВКЛ
Ошибка при загрузке ЧЕРН ВКЛ
Ошибки

Файл: РАСТАЧ,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке РАСТАЧ,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: ЗОНА ПРЧС,8,5
Ошибка при загрузке ЗОНА ПРЧС,8,5
Ошибки

Файл: ПРИПУСК 0.5,0
Ошибка при загрузке ПРИПУСК 0.5,0
Ошибки

Файл: ЧЕРН ВЫКЛ
Ошибка при загрузке ЧЕРН ВЫКЛ
Ошибки

Файл: РАСТАЧ,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке РАСТАЧ,ППЕР,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: ЗОНА ПОЧС,4,6
Ошибка при загрузке ЗОНА ПОЧС,4,6
Ошибки

Файл: ПРИПУСК 0,0
Ошибка при загрузке ПРИПУСК 0,0
Ошибки

Файл: КРОМКА ГЛАВН
Ошибка при загрузке КРОМКА ГЛАВН
Ошибки

Файл: РАСТАЧ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибка при загрузке РАСТАЧ,ПРОД,ОТКР,ЦИКЛ ВЫКЛ
Ошибки

Файл: КОНЕЦ
Ошибка при загрузке КОНЕЦ
Ошибки
